

export default function About() {
    
    return <div className=" flex w-2/3 mx-auto mt-10">
    Ice cream lemon drops bonbon sugar plum toffee macaroon toffee lemon drops dragée. Chocolate bar chupa chups macaroon sugar plum shortbread sesame snaps cake liquorice cake. Biscuit cheesecake cupcake cake tiramisu croissant. Lollipop pudding pudding chocolate bar lemon drops marzipan halvah marshmallow danish. Apple pie gummies liquorice caramels ice cream. Marzipan donut cheesecake ice cream ice cream macaroon halvah. Chupa chups powder powder marshmallow marshmallow chupa chups liquorice topping cupcake. Caramels tiramisu chocolate bear claw donut brownie danish jelly-o. Gummi bears jelly beans caramels chocolate bar shortbread. Chocolate cake tootsie roll shortbread cupcake jelly-o pastry dragée chocolate. Cheesecake gummi bears fruitcake sugar plum chocolate sugar plum. Icing cookie sweet roll biscuit sugar plum chocolate bar jelly beans apple pie toffee. Chocolate cake candy gingerbread marzipan macaroon donut.

Halvah tart croissant carrot cake icing chocolate bar cupcake cheesecake fruitcake. Gummi bears muffin chocolate cake lemon drops cake icing dragée. Caramels powder sweet shortbread topping pudding. Lollipop lollipop brownie pudding ice cream tart fruitcake cheesecake. Lollipop bear claw cake pie chocolate cake chocolate bar toffee biscuit. Gummies gummies dragée sweet muffin lollipop. Sugar plum chocolate bar cotton candy cheesecake bear claw. Cupcake apple pie macaroon tootsie roll sweet roll tart. Lemon drops icing candy ice cream marshmallow sweet roll oat cake tootsie roll. Croissant topping topping fruitcake croissant cake. Tiramisu chocolate bar caramels ice cream donut marzipan donut sugar plum. Toffee marzipan sesame snaps sweet cake pie cupcake donut candy canes. Gingerbread pie cupcake pastry chocolate bar. Tart lollipop tart apple pie tiramisu fruitcake.

Soufflé jelly beans chocolate bar pastry cake. Tart marzipan tootsie roll cake cotton candy. Cotton candy fruitcake dessert sugar plum gummi bears dragée jelly donut. Jelly beans oat cake candy canes biscuit oat cake gummies. Chocolate cake topping pie caramels bonbon jelly lollipop. Lollipop gummies donut donut cake. Candy chocolate bar pie gummies tart. Tootsie roll gingerbread halvah sugar plum muffin. Cupcake icing dragée cookie dessert marzipan jelly-o chupa chups. Marzipan jelly beans dessert pie soufflé cheesecake liquorice gummies chocolate cake. Cotton candy apple pie tiramisu apple pie cheesecake lollipop jujubes. Dragée donut cupcake dessert cake icing toffee tart. Fruitcake pastry powder tart cookie. Caramels lemon drops jelly beans gingerbread cookie muffin biscuit muffin jelly.<br />
     <br />
     Ice cream lemon drops bonbon sugar plum toffee macaroon toffee lemon drops dragée. Chocolate bar chupa chups macaroon sugar plum shortbread sesame snaps cake liquorice cake. Biscuit cheesecake cupcake cake tiramisu croissant. Lollipop pudding pudding chocolate bar lemon drops marzipan halvah marshmallow danish. Apple pie gummies liquorice caramels ice cream. Marzipan donut cheesecake ice cream ice cream macaroon halvah. Chupa chups powder powder marshmallow marshmallow chupa chups liquorice topping cupcake. Caramels tiramisu chocolate bear claw donut brownie danish jelly-o. Gummi bears jelly beans caramels chocolate bar shortbread. Chocolate cake tootsie roll shortbread cupcake jelly-o pastry dragée chocolate. Cheesecake gummi bears fruitcake sugar plum chocolate sugar plum. Icing cookie sweet roll biscuit sugar plum chocolate bar jelly beans apple pie toffee. Chocolate cake candy gingerbread marzipan macaroon donut.

Halvah tart croissant carrot cake icing chocolate bar cupcake cheesecake fruitcake. Gummi bears muffin chocolate cake lemon drops cake icing dragée. Caramels powder sweet shortbread topping pudding. Lollipop lollipop brownie pudding ice cream tart fruitcake cheesecake. Lollipop bear claw cake pie chocolate cake chocolate bar toffee biscuit. Gummies gummies dragée sweet muffin lollipop. Sugar plum chocolate bar cotton candy cheesecake bear claw. Cupcake apple pie macaroon tootsie roll sweet roll tart. Lemon drops icing candy ice cream marshmallow sweet roll oat cake tootsie roll. Croissant topping topping fruitcake croissant cake. Tiramisu chocolate bar caramels ice cream donut marzipan donut sugar plum. Toffee marzipan sesame snaps sweet cake pie cupcake donut candy canes. Gingerbread pie cupcake pastry chocolate bar. Tart lollipop tart apple pie tiramisu fruitcake.

Soufflé jelly beans chocolate bar pastry cake. Tart marzipan tootsie roll cake cotton candy. Cotton candy fruitcake dessert sugar plum gummi bears dragée jelly donut. Jelly beans oat cake candy canes biscuit oat cake gummies. Chocolate cake topping pie caramels bonbon jelly lollipop. Lollipop gummies donut donut cake. Candy chocolate bar pie gummies tart. Tootsie roll gingerbread halvah sugar plum muffin. Cupcake icing dragée cookie dessert marzipan jelly-o chupa chups. Marzipan jelly beans dessert pie soufflé cheesecake liquorice gummies chocolate cake. Cotton candy apple pie tiramisu apple pie cheesecake lollipop jujubes. Dragée donut cupcake dessert cake icing toffee tart. Fruitcake pastry powder tart cookie. Caramels lemon drops jelly beans gingerbread cookie muffin biscuit muffin jelly.
</div>
};
